### ISSUE TITLE
Single word Queries give "Please fill a valid search query" or "begin X, end XXX, length XX" or no matches

### ISSUE THREAD

**Issue by Samir55** [hemoali/SearchEngine#18]
For Example, queries like:
ACM
google
codeforces

**Comment by OmarBazaraa** [comment]
Did you re-crawl the web?
We changed the way of stemming words. So this way should be reflected in the database as well.

**Comment by Samir55** [comment]
Yes recrawled

**Comment by OmarBazaraa** [comment]
Fixed in 114d95658e9a9f0551eb242996aa98dee3b2bf80
